# -*- coding: utf-8 -*-
"""wine_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10Jez-kY-haeYXQrAhg8KVHb6WJvOZaMY

##**Streamlit Wine Quality Classifier App**
By Aleena Salahuddin
BIA Batch 10

dataset: [link text](https://https://www.kaggle.com/datasets/piyushagni5/white-wine-quality)


---


Made using Python, Scikit-learn & Streamlit

**1. Install Dependancies**
"""

!pip install streamlit plotly  scikit-learn joblib

import pandas as pd
import tensorflow as tf
import streamlit as st
from PIL import Image
import numpy as np
import matplotlib as plt
import matplotlib.pyplot as plt
import plotly.express as px
import seaborn as sns
import plotly.graph_objects as go
import plotly.express as px
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from collections import Counter

from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report
from sklearn.preprocessing import LabelEncoder, StandardScaler
import sys
print(sys.path)

"""**2. Load & Inspect Data**"""

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('/content/drive/MyDrive/wine-quality-dataset/winequality-white.csv', delimiter=';')

#dislay first 5 rows
print(df.head(5))

#check for missing values, clean if found any
print(df.info())
print("Total nulls: ", df.isna().sum().sum())
df['quality'].unique()

"""**3. Label Encoding**"""

encoder = LabelEncoder()
df['quality'] = encoder.fit_transform(df['quality'])
{index: label for index, label in enumerate(encoder.classes_)}

"""**4. Visualization**

Correlation Heatmap
"""

corr = df.corr()
plt.figure(figsize=(12, 10))
sns.heatmap(corr, annot=True, vmin=-1.0, vmax = 1.0)
plt.show()

"""**Model Training: Train, test, split**"""

y = pd.qcut(df['quality'], q=2, labels=[0, 1])
X = df.drop('quality', axis=1)

scaler = StandardScaler()
X = pd.DataFrame(scaler.fit_transform(X), columns=X.columns)
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8, random_state=34)

# Convert y_train and y_test to integer dtype
y_train = y_train.astype(int)
y_test = y_test.astype(int)

num_feat = X.shape[1]
num_class = len(y.unique())
print(num_feat, num_class)

#TensorFlow
inputs = tf.keras.Input(shape=(num_feat,))
x = tf.keras.layers.Dense(64, activation='relu')(inputs)
x = tf.keras.layers.Dense(num_feat, activation='relu')(x)
outputs = tf.keras.layers.Dense(1, activation='sigmoid')(x)

model = tf.keras.Model(inputs=inputs, outputs=outputs)
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

history = model.fit(X_train, y_train, validation_split=0.2, batch_size=32, epochs=10)
model.evaluate(X_test, y_test)

"""**5. Evaluation**"""

y_pred = np.round(model.predict(X_test))
print(classification_report(y_test, y_pred))

"""**Streamlit Web App UI**"""

# --- App Title Section ---
st.set_page_config(page_title="Wine Quality Predictor", page_icon="🍷", layout="wide")

st.markdown(
    """
    <div style="text-align:center; padding:1rem 0;">
        <h1 style="color:#8E4585; font-size:2.5rem;">🍷 Wine Quality Prediction</h1>
        <p style="color:#555; font-size:1.1rem;">
            Analyze wine characteristics and predict its quality — powered by Machine Learning.
        </p>
    </div>
    """,
    unsafe_allow_html=True,
)

# --- Optional Hero Banner (replace URL if you like) ---
st.image(
    "https://images.unsplash.com/photo-1601924638867-3ec6c8b1b2ce?auto=format&fit=crop&w=1200&q=80",
    use_column_width=True,
    caption="Explore how subtle chemical properties define wine excellence 🍇"
)

# --- Layout: Columns for Overview + Data Peek ---
col1, col2 = st.columns([1.5, 1])

with col1:
    st.markdown("### 📊 Dataset Overview")
    st.dataframe(df.head(10))

with col2:
    st.markdown("### 🔍 Key Statistics")
    st.metric("Rows", df.shape[0])
    st.metric("Columns", df.shape[1])
    st.metric("Unique Quality Levels", len(df['quality'].unique()))

# --- Divider ---
st.markdown("---")

# --- Visualization Section Header ---
st.markdown(
    "<h2 style='text-align:center; color:#8E4585;'>Data Visualizations</h2>",
    unsafe_allow_html=True,
)

with st.sidebar:
    st.markdown("## ⚙️ Controls")
    st.info("Use sliders to adjust input values and predict wine quality below ↓")

# display table of the data
st.subheader('Data Visualization')
st.dataframe(df)

st.markdown('<h3>Heatmaps</h3>', unsafe_allow_html=True)


corr = df.corr()
plt.figure(figsize=(12, 10))
sns.heatmap(corr, annot=True, vmin=-1.0, vmax = 1.0)
plt.show()
st.pyplot()

#line chart
st.markdown('<h3>Line Chart</h3>', unsafe_allow_html=True)
st.line_chart(df, x='quality', y='alcohol')

#area chart
st.markdown('<h3>Area Chart</h3>', unsafe_allow_html=True)
st.area_chart(df, x='quality', y='alcohol')

#bar chart
st.markdown('<h3>Bar Chart</h3>', unsafe_allow_html=True)
st.bar_chart(df, x='quality', y='alcohol')

# Create a pie chart using Matplotlib
st.markdown('<h3>Pie Chart</h3>', unsafe_allow_html=True)
st.markdown('<h6>[A darker color in the chart indicates a stronger relationship between the attribute and the wine quality]</h6>', unsafe_allow_html=True)
plt.pie(df['alcohol'], labels=df['quality'])
# Display the pie chart in Streamlit
st.pyplot()

#Sidebar Input Widgets
st.sidebar.title("Input Values")
fixed_acidity = st.sidebar.slider("Fixed acidity:", 0.0, 1.0, 0.5)
volatile_acidity = st.sidebar.slider("Volatile acidity:", 0.0, 1.0, 0.5)
citric_acid = st.sidebar.slider("Citric acid:", 0.0, 1.0, 0.5)
residual_sugar = st.sidebar.slider("Residual sugar:", 0.0, 1.0, 0.5)
chlorides = st.sidebar.slider("Chlorides:", 0.0, 1.0, 0.5)
free_sulfur_dioxide = st.sidebar.slider("Free sulfur dioxide:", 0.0, 1.0, 0.5)
total_sulfur_dioxide = st.sidebar.slider("Total sulfur dioxide:", 0.0, 1.0, 0.5)
density = st.sidebar.slider("Density:", 0.0, 1.0, 0.5)
pH = st.sidebar.slider("pH:", 0.0, 1.0, 0.5)
sulphates = st.sidebar.slider("Sulphates:", 0.0, 1.0, 0.5)
alcohol = st.sidebar.slider("Alcohol:", 0.0, 1.0, 0.5)

"""**Model Retraining Function**: Interactive visualization using a slider."""

def train_model():
    inputs = tf.keras.Input(shape=(num_feat,))
    x = tf.keras.layers.Dense(64, activation='relu')(inputs)
    x = tf.keras.layers.Dense(num_feat, activation='relu')(x)
    outputs = tf.keras.layers.Dense(1, activation='sigmoid')(x)
    model = tf.keras.Model(inputs=inputs, outputs=outputs)
    model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
    model.fit(X_train, y_train, validation_split=0.2, batch_size=32, epochs=10)
    return model

model = train_model()

# Create a data frame with the values from the sliders
input_data = pd.DataFrame({
    "fixed_acidity": [fixed_acidity],
    "volatile_acidity": [volatile_acidity],
    "citric_acid": [citric_acid],
    "residual_sugar": [residual_sugar],
    "chlorides": [chlorides],
    "free_sulfur_dioxide": [free_sulfur_dioxide],
    "total_sulfur_dioxide": [total_sulfur_dioxide],
    "density": [density],
    "pH": [pH],
    "sulphates": [sulphates],
    "alcohol": [alcohol]
})

# Define the map_prediction_to_label function
def map_prediction_to_label(prediction):
    """Map a prediction to a quality label.

    Args:
        prediction (int): The prediction to map to a label.

    Returns:
        str: The label corresponding to the prediction.
    """
     # Determine the quality label based on the values of the sliders
    if prediction == 1 and fixed_acidity < 7 and volatile_acidity < 0.5 and citric_acid > 0.2 and residual_sugar < 1 and chlorides < 0.06 and free_sulfur_dioxide > 20 and total_sulfur_dioxide > 50 and density > 0.99 and pH > 3 and sulphates > 0.5 and alcohol > 9:
        return "High"
    elif prediction == 1 and fixed_acidity < 7 and volatile_acidity < 0.5 and citric_acid > 0.2 and residual_sugar < 1 and chlorides < 0.06 and free_sulfur_dioxide > 20 and total_sulfur_dioxide > 50 and density > 0.99 and pH > 3 and sulphates > 0.5 and alcohol > 6:
        return "Average"
    else:
        return "Low"

# Use the model to make a prediction on the input data
prediction = model.predict(input_data)

# Round the predicted values to the nearest integer
prediction = np.round(prediction)

# Map the prediction to a quality label
quality_label = map_prediction_to_label(prediction)

# Display the predicted quality label on the Streamlit app
st.write("Wine quality:", quality_label)

"""**Present the results using a bar chart**"""

# Use the model to make a prediction on the input data
prediction = model.predict(input_data)

# Round the predicted values to the nearest integer
prediction = np.round(prediction)

# Map the prediction to a quality label
quality_labels = []
for p in prediction:
    quality_labels.append(map_prediction_to_label(p))

# Count the number of predictions for each quality label
counts = dict(Counter(quality_labels))

# Create a dataframe from the counts
counts_df = pd.DataFrame({'Quality': list(counts.keys()), 'Count': list(counts.values())})

# Display the counts as a bar chart
st.bar_chart(counts_df)